name: build
on:
  repository_dispatch:
    types: ["build"]
  push:
    tags-ignore:
      - '*'
    branches:
      - master
  issues:
    types: [closed]

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_REPO: ${{ secrets.GH_REPO }}


jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.10.4

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # see https://github.com/actions/setup-python
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/setup-node@v3
      id: setup-node
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      id: setup-pnpm
      with:
        version: 6.0.2

    - name: Install requirements
      id: install-requirements
      run: |
        pip install PyGithub requests

    - name: Export issue
      id: export-issue
      run: |
        python3 .github/issue.py

    - name: Export site
      id: export-site
      run: |
        pnpm install
        pnpm export

    - name: Auto Commit
      id: auto-commit
      run: |
        git config --global user.email "dylanninin@gmail.com"
        git config --global user.name "Dylanninin"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "update post - skip ci"
          git push origin master
        else
          echo "clean"
        fi
